<%@ Page Title="" Language="C#" MasterPageFile="~/Admin/AdminMasterPage.master" AutoEventWireup="true"
    CodeFile="Admin_FAQ.aspx.cs" Inherits="Admin_Admin_FAQ" %>

<%@ OutputCache VaryByParam="none" Duration="1" NoStore="true" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="Server">
    <fieldset style="width: auto; height: auto; background-color: #d5fefd; background-image: linear-gradient(315deg, #d5fefd 0%, #fffcff 74%);">
        <legend>
            <h2 class="shadow3">
            </h2>
        </legend>
        <center>
            <style>
                .shadow3
                {
                    color: black;
                    font: bold 30px Helvetica, Arial, Sans-Serif;
                    text-shadow: 1px 1px white, 2px 2px white, 3px 3px white;
                }
                .shadow3:hover
                {
                    position: relative;
                    top: -3px;
                    left: -3px;
                    text-shadow: 1px 1px white, 2px 2px white, 3px 3px white, 4px 4px white, 5px 5px white, 6px 6px white;
                }
            </style>
            <h4 class="shadow3">
                FAQ</h4>
    </fieldset>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
    <asp:LinkButton ID="Add_FAQ" runat="server" OnClick="Add_FAQ_Click"> <h2> Add FAQ</h2></asp:LinkButton>
    <br />
    <asp:GridView ID="faq_GridView" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True"
        AutoGenerateEditButton="True" DataSourceID="faq_SqlDataSource" Style="background-color: #fefefe;
        background-image: linear-gradient(315deg, #fefefe 0%, #00a4e4 74%);" DataKeyNames="Faq_id">
        <Columns>
            <asp:BoundField DataField="Faq_id" HeaderText="Faq_id" SortExpression="Faq_id" InsertVisible="False"
                ReadOnly="True" />
            <asp:BoundField DataField="Faq_que" HeaderText="Faq_que" SortExpression="Faq_que" />
            <asp:BoundField DataField="Faq_ans" HeaderText="Faq_ans" SortExpression="Faq_ans" />
        </Columns>
    </asp:GridView>
    <asp:SqlDataSource ID="faq_SqlDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>"
        SelectCommand="SELECT * FROM [FAQ]" DeleteCommand="Delete from FAQ where Faq_id=@Faq_id;"
        UpdateCommand="Update FAQ set Faq_que=@Faq_que,Faq_ans=@Faq_ans where Faq_id=@Faq_id;">
        <DeleteParameters>
            <asp:ControlParameter ControlID="faq_GridView" Name="Faq_id" PropertyName="SelectedValue" />
        </DeleteParameters>
        <UpdateParameters>
            <asp:ControlParameter ControlID="faq_GridView" Name="Faq_que" PropertyName="SelectedValue" />
            <asp:ControlParameter ControlID="faq_GridView" Name="Faq_ans" PropertyName="SelectedValue" />
            <asp:ControlParameter ControlID="faq_GridView" Name="Faq_id" PropertyName="SelectedValue" />
        </UpdateParameters>
    </asp:SqlDataSource>
    </fieldset> </center>
</asp:Content>
