<%@ Page Title="" Language="C#" MasterPageFile="~/Admin/AdminMasterPage.master" AutoEventWireup="true"
    CodeFile="Admin_AboutUs.aspx.cs" Inherits="Admin_Admin_AboutUs" %>
      <%@ OutputCache VaryByParam="none" Duration=1 NoStore="true" %>

<%@ OutputCache VaryByParam="none" Duration="1" NoStore="true" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="Server">
<fieldset style="width: auto; height: auto; background-color: #d5fefd;
background-image: linear-gradient(315deg, #d5fefd 0%, #fffcff 74%);">
            <legend>
                <h2 class="shadow3">
                   </h2>
            </legend>
    <center>
    <style>
        .shadow3
        {
            color: black;
            font: bold 30px Helvetica, Arial, Sans-Serif;
            text-shadow: 1px 1px white, 2px 2px white, 3px 3px white;
        }
        .shadow3:hover
        {
            position: relative;
            top: -3px;
            left: -3px;
            text-shadow: 1px 1px white, 2px 2px white, 3px 3px white, 4px 4px white, 5px 5px white, 6px 6px white;
        }
    </style>
    <h4 class="shadow3">
        About Us</h4>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
   
                <asp:LinkButton ID="addAboutUs" runat="server" OnClick="addAboutUs_Click"> <h2> Add AboutUs </h2></asp:LinkButton>
                <br />
                <br />
                <br />
                <asp:GridView ID="A_GridView" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True"
                    AutoGenerateEditButton="True" DataSourceID="A_SqlDataSource" CellPadding="2" style="background-color: #fefefe;
background-image: linear-gradient(315deg, #fefefe 0%, #00a4e4 74%);"
                    ForeColor="white" GridLines="Horizontal" BackColor="#2E86C1" BorderColor="black"
                    BorderWidth="4px" DataKeyNames="A_id">
                    <AlternatingRowStyle BackColor="#2E86C1" />
                    <Columns>
                        <asp:BoundField DataField="A_id" HeaderText="A_id" SortExpression="A_id" InsertVisible="False"
                            ReadOnly="True" />
                        <asp:BoundField DataField="A_desc" HeaderText="A_desc" SortExpression="A_desc" />
                        <asp:ImageField HeaderText="A_img" DataImageUrlField="A_img" ControlStyle-Width="280px"
                            ControlStyle-Height="280px" />
                    </Columns>
                    <FooterStyle BackColor="#2E86C1" />
                    <HeaderStyle BackColor="#1B4F72" Font-Bold="True" />
                    <PagerStyle BackColor="PaleGoldenrod" ForeColor="DarkSlateBlue" HorizontalAlign="Center" />
                    <SelectedRowStyle BackColor="DarkSlateBlue" ForeColor="GhostWhite" />
                    <SortedAscendingCellStyle BackColor="#FAFAE7" />
                    <SortedAscendingHeaderStyle BackColor="#DAC09E" />
                    <SortedDescendingCellStyle BackColor="#E1DB9C" />
                    <SortedDescendingHeaderStyle BackColor="#C2A47B" />
                </asp:GridView>
                <asp:SqlDataSource ID="A_SqlDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>"
                    SelectCommand="SELECT * FROM [AboutUs]" DeleteCommand=" Delete from AboutUs where A_id=@A_id;"
                    InsertCommand="INSERT INTO [AboutUs] ([A_desc], [A_img]) VALUES (@A_desc, @A_img)"
                    UpdateCommand="Update AboutUs set A_desc=@A_desc where A_id=@A_id;">
                    <DeleteParameters>
                        <asp:ControlParameter ControlID="A_GridView" Name="A_id" PropertyName="SelectedValue" />
                    </DeleteParameters>
                    <InsertParameters>
                        <asp:Parameter Name="A_desc" Type="String" />
                        <asp:Parameter Name="A_img" Type="String" />
                    </InsertParameters>
                    <UpdateParameters>
                        <asp:ControlParameter ControlID="A_GridView" Name="A_desc" PropertyName="SelectedValue" />
                        <asp:ControlParameter ControlID="A_GridView" Name="A_id" PropertyName="SelectedValue" />
                    </UpdateParameters>
                </asp:SqlDataSource>
            </center>
</asp:Content>
