<%@ Page Title="" Language="C#" MasterPageFile="~/Admin/AdminMasterPage.master" AutoEventWireup="true"
    CodeFile="Admin_Consultation.aspx.cs" Inherits="Admin_Admin_Consultation" %>

<%@ OutputCache VaryByParam="none" Duration="1" NoStore="true" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="Server">
    <fieldset style="width: auto; height: auto; background-color: #d5fefd; background-image: linear-gradient(315deg, #d5fefd 0%, #fffcff 74%);">
        <legend>
            <h2 class="shadow3">
            </h2>
        </legend>
        <center>
            <style>
                .shadow3
                {
                    color: black;
                    font: bold 30px Helvetica, Arial, Sans-Serif;
                    text-shadow: 1px 1px white, 2px 2px white, 3px 3px white;
                }
                .shadow3:hover
                {
                    position: relative;
                    top: -3px;
                    left: -3px;
                    text-shadow: 1px 1px white, 2px 2px white, 3px 3px white, 4px 4px white, 5px 5px white, 6px 6px white;
                }
            </style>
            <h4 class="shadow3">
                Consultation</h4>
    </fieldset>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
    <center>
        <asp:GridView ID="Co_GridView" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True"
            DataSourceID="Co_SqlDataSource" DataKeyNames="Co_id" Style="background-image: linear-gradient(315deg, #fefefe 0%, #00a4e4 74%);">
            <Columns>
                <asp:BoundField DataField="Co_id" HeaderText="Co_id" SortExpression="Co_id" InsertVisible="False"
                    ReadOnly="True" />
                <asp:BoundField DataField="Co_desc" HeaderText="Co_desc" SortExpression="Co_desc" />
                <asp:BoundField DataField="Co_fnm" HeaderText="Co_fnm" SortExpression="Co_fnm" />
                <asp:BoundField DataField="Co_lnm" HeaderText="Co_lnm" SortExpression="Co_lnm" />
                <asp:BoundField DataField="Co_gender" HeaderText="Co_gender" SortExpression="Co_gender" />
                <asp:BoundField DataField="Co_complaint" HeaderText="Co_complaint" SortExpression="Co_complaint" />
                <asp:BoundField DataField="Co_allergies" HeaderText="Co_allergies" SortExpression="Co_allergies" />
                <asp:BoundField DataField="Co_otherque" HeaderText="Co_otherque" SortExpression="Co_otherque" />
                <asp:BoundField DataField="Co_phn" HeaderText="Co_phn" SortExpression="Co_phn" />
                <asp:BoundField DataField="Co_email" HeaderText="Co_email" SortExpression="Co_email" />
            </Columns>
        </asp:GridView>
        <asp:SqlDataSource ID="Co_SqlDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>"
            SelectCommand="SELECT * FROM [Consultation]" DeleteCommand=" Delete from Consultation where Co_id=@Co_id;">
            <DeleteParameters>
                <asp:ControlParameter ControlID="Co_GridView" Name="Co_id" PropertyName="SelectedValue" />
            </DeleteParameters>
        </asp:SqlDataSource>
    </center>
</asp:Content>
