<%@ Page Title="" Language="C#" MasterPageFile="~/Admin/AdminMasterPage.master" AutoEventWireup="true"
    CodeFile="Admin_Category.aspx.cs" Inherits="Admin_Admin_Category" %>

<%@ OutputCache VaryByParam="none" Duration="1" NoStore="true" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
    <center>
        <asp:LinkButton ID="addcategory" runat="server" OnClick="addcategory_Click">Add Category</asp:LinkButton>
        <br />
        <br />
        <asp:GridView ID="Cat_GridView" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True"
            AutoGenerateEditButton="True" DataSourceID="Cat_SqlDataSource" DataKeyNames="Cat_id"
            Style="background-image: linear-gradient(315deg, #fefefe 0%, #00a4e4 74%);">
            <Columns>
                <asp:BoundField DataField="Cat_id" HeaderText="Cat_id" InsertVisible="False" ReadOnly="True"
                    SortExpression="Cat_id" />
                <asp:BoundField DataField="Cat_name" HeaderText="Cat_name" SortExpression="Cat_name" />
                <asp:ImageField DataImageUrlField="Cat_img" HeaderText="Cat_img" SortExpression="Cat_img">
                </asp:ImageField>
            </Columns>
        </asp:GridView>
        <asp:SqlDataSource ID="Cat_SqlDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>"
            DeleteCommand="Delete from Category where Cat_id=@Cat_id;" SelectCommand="SELECT * FROM [Category]"
            UpdateCommand="update Category set Cat_name=@Cat_name,Cat_img=@Cat_img where Cat_id=@Cat_id;">
            <DeleteParameters>
                <asp:ControlParameter ControlID="Cat_GridView" Name="Cat_id" PropertyName="SelectedValue" />
            </DeleteParameters>
            <UpdateParameters>
                <asp:ControlParameter ControlID="Cat_GridView" Name="Cat_name" PropertyName="SelectedValue" />
                <asp:ControlParameter ControlID="Cat_GridView" Name="Cat_img" PropertyName="SelectedValue" />
                <asp:ControlParameter ControlID="Cat_GridView" Name="Cat_id" PropertyName="SelectedValue" />
            </UpdateParameters>
        </asp:SqlDataSource>
    </center>
</asp:Content>
