<%@ Page Title="" Language="C#" MasterPageFile="~/Admin/AdminMasterPage.master" AutoEventWireup="true"
    CodeFile="Admin_Franchise.aspx.cs" Inherits="Admin_Admin_Franchise" %>

<%@ OutputCache VaryByParam="none" Duration="1" NoStore="true" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="Server">
    <fieldset style="width: auto; height: auto; background-color: #d5fefd; background-image: linear-gradient(315deg, #d5fefd 0%, #fffcff 74%);">
        <legend>
            <h2 class="shadow3">
            </h2>
        </legend>
        <center>
            <style>
                .shadow3
                {
                    color: black;
                    font: bold 30px Helvetica, Arial, Sans-Serif;
                    text-shadow: 1px 1px white, 2px 2px white, 3px 3px white;
                }
                .shadow3:hover
                {
                    position: relative;
                    top: -3px;
                    left: -3px;
                    text-shadow: 1px 1px white, 2px 2px white, 3px 3px white, 4px 4px white, 5px 5px white, 6px 6px white;
                }
            </style>
            <h4 class="shadow3">
                Franchise</h4>
    </fieldset>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
    <asp:LinkButton ID="AddP" runat="server" OnClick="AddP_Click"> <h2> Add Franchise Info</h2></asp:LinkButton>
    <br />
    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True"
        AutoGenerateEditButton="True" DataSourceID="FInfo_SqlDataSource" Style="background-color: #fefefe;
        background-image: linear-gradient(315deg, #fefefe 0%, #00a4e4 74%);" DataKeyNames="Fr_id">
        <Columns>
            <asp:BoundField DataField="Fr_id" HeaderText="Fr_id" SortExpression="Fr_id" InsertVisible="False"
                ReadOnly="True" />
            <asp:BoundField DataField="Fr_desc1" HeaderText="Fr_desc1" SortExpression="Fr_desc1" />
            <asp:BoundField DataField="Fr_desc2" HeaderText="Fr_desc2" SortExpression="Fr_desc2" />
            <asp:BoundField DataField="Fr_desc3" HeaderText="Fr_desc3" SortExpression="Fr_desc3" />
            <asp:ImageField HeaderText="Fr_img" DataImageUrlField="Fr_img" ControlStyle-Width="280px"
                ControlStyle-Height="280px">
                <ControlStyle Height="280px" Width="280px"></ControlStyle>
            </asp:ImageField>
        </Columns>
    </asp:GridView>
    <asp:SqlDataSource ID="FInfo_SqlDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>"
        SelectCommand="SELECT * FROM [Franchise_info]" DeleteCommand=" Delete from Franchise_info where Fr_id=@Fr_id;"
        UpdateCommand="Update Franchise_info set Fr_desc1=@Fr_desc1,Fr_desc2=@Fr_desc2,Fr_desc3=@Fr_desc3,Fr_img=@Fr_img where Fr_id=@Fr_id;">
        <DeleteParameters>
            <asp:ControlParameter Name="Fr_id" ControlID="GridView1" PropertyName="SelectedValue" />
        </DeleteParameters>
        <UpdateParameters>
            <asp:ControlParameter ControlID="GridView1" Name="Fr_desc1" PropertyName="SelectedValue" />
            <asp:ControlParameter ControlID="GridView1" Name="Fr_desc2" PropertyName="SelectedValue" />
            <asp:ControlParameter ControlID="GridView1" Name="Fr_desc3" PropertyName="SelectedValue" />
            <asp:ControlParameter ControlID="GridView1" Name="Fr_desc4" PropertyName="SelectedValue" />
            <asp:ControlParameter ControlID="GridView1" Name="Fr_id" PropertyName="SelectedValue" />
        </UpdateParameters>
    </asp:SqlDataSource>
    </center>
</asp:Content>
