<%@ Page Title="" Language="C#" MasterPageFile="~/Admin/AdminMasterPage.master" AutoEventWireup="true"
    CodeFile="Admin_TermsAndConditions.aspx.cs" Inherits="Admin_Admin_TermsAndConditions" %>

<%@ OutputCache VaryByParam="none" Duration="1" NoStore="true" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="Server">
    <fieldset style="width: auto; height: auto; background-color: #d5fefd; background-image: linear-gradient(315deg, #d5fefd 0%, #fffcff 74%);">
        <legend>
            <h2 class="shadow3">
            </h2>
        </legend>
        <center>
            <style>
                .shadow3
                {
                    color: black;
                    font: bold 30px Helvetica, Arial, Sans-Serif;
                    text-shadow: 1px 1px white, 2px 2px white, 3px 3px white;
                }
                .shadow3:hover
                {
                    position: relative;
                    top: -3px;
                    left: -3px;
                    text-shadow: 1px 1px white, 2px 2px white, 3px 3px white, 4px 4px white, 5px 5px white, 6px 6px white;
                }
            </style>
            <h4 class="shadow3">
                Terms And Conditions</h4>
    </fieldset>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
    <asp:LinkButton ID="AddTD" runat="server" OnClick="AddTD_Click"> <h2> Add Terms And Conditions</h2></asp:LinkButton>
    <br />
    <br />
    <asp:GridView ID="T_GridView" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True"
        AutoGenerateEditButton="True" DataSourceID="T_SqlDataSource" Style="background-color: #fefefe;
        background-image: linear-gradient(315deg, #fefefe 0%, #00a4e4 74%);" DataKeyNames="T_id">
        <Columns>
            <asp:BoundField DataField="T_id" HeaderText="T_id" SortExpression="T_id" InsertVisible="False"
                ReadOnly="True" />
            <asp:BoundField DataField="T_desc1" HeaderText="T_desc1" SortExpression="T_desc1" />
            <asp:BoundField DataField="T_desc2" HeaderText="T_desc2" SortExpression="T_desc2" />
            <asp:BoundField DataField="T_desc3" HeaderText="T_desc3" SortExpression="T_desc3" />
            <asp:BoundField DataField="T_desc4" HeaderText="T_desc4" SortExpression="T_desc4" />
            <asp:BoundField DataField="T_desc5" HeaderText="T_desc5" SortExpression="T_desc5" />
            <asp:BoundField DataField="T_desc6" HeaderText="T_desc6" SortExpression="T_desc6" />
            <asp:BoundField DataField="T_desc7" HeaderText="T_desc7" SortExpression="T_desc7" />
            <asp:ImageField HeaderText="T_img" DataImageUrlField="T_img" ControlStyle-Width="280px"
                ControlStyle-Height="280px">
                <ControlStyle Height="280px" Width="280px"></ControlStyle>
            </asp:ImageField>
        </Columns>
    </asp:GridView>
    <asp:SqlDataSource ID="T_SqlDataSource" runat="server" ConnectionString="
        <%$ ConnectionStrings:ConnectionString %>" SelectCommand="SELECT * FROM [TermsAndCondition]"
        DeleteCommand=" Delete from TermsAndCondition where T_id=@T_id;" UpdateCommand="Update TermsAndCondition set T_desc1=@T_desc1,T_desc2=@T_desc2,T_desc3=@T_desc3,T_img=@T_img where T_id=@T_id;">
        <DeleteParameters>
            <asp:ControlParameter ControlID="T_GridView" Name="T_id" PropertyName="SelectedValue" />
        </DeleteParameters>
        <UpdateParameters>
            <asp:ControlParameter ControlID="T_GridView" Name="T_desc1" PropertyName="SelectedValue" />
            <asp:ControlParameter ControlID="T_GridView" Name="T_desc2" PropertyName="SelectedValue" />
            <asp:ControlParameter ControlID="T_GridView" Name="T_desc3" PropertyName="SelectedValue" />
            <asp:ControlParameter ControlID="T_GridView" Name="T_des4" PropertyName="SelectedValue" />
            <asp:ControlParameter ControlID="T_GridView" Name="T_desc5" PropertyName="SelectedValue" />
            <asp:ControlParameter ControlID="T_GridView" Name="T_desc6" PropertyName="SelectedValue" />
            <asp:ControlParameter ControlID="T_GridView" Name="T_desc7" PropertyName="SelectedValue" />
            <asp:ControlParameter ControlID="T_GridView" Name="T_img" PropertyName="SelectedValue" />
            <asp:ControlParameter ControlID="T_GridView" Name="T_id" PropertyName="SelectedValue" />
        </UpdateParameters>
    </asp:SqlDataSource>
    </center>
</asp:Content>
