<%@ Page Title="" Language="C#" MasterPageFile="~/Admin/AdminMasterPage.master" AutoEventWireup="true"
    CodeFile="Admin_DiagnosticTests.aspx.cs" Inherits="Admin_Admin_DiagnosticTests" %>

<%@ OutputCache VaryByParam="none" Duration="1" NoStore="true" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="Server">
    <fieldset style="width: auto; height: auto; background-color: #d5fefd; background-image: linear-gradient(315deg, #d5fefd 0%, #fffcff 74%);">
        <legend>
            <h2 class="shadow3">
            </h2>
        </legend>
        <center>
            <style>
                .shadow3
                {
                    color: black;
                    font: bold 30px Helvetica, Arial, Sans-Serif;
                    text-shadow: 1px 1px white, 2px 2px white, 3px 3px white;
                }
                .shadow3:hover
                {
                    position: relative;
                    top: -3px;
                    left: -3px;
                    text-shadow: 1px 1px white, 2px 2px white, 3px 3px white, 4px 4px white, 5px 5px white, 6px 6px white;
                }
            </style>
            <h4 class="shadow3">
                Diagnostic Tests</h4>
    </fieldset>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
    <center>
        <asp:LinkButton ID="addContactus" runat="server" OnClick="addContactus_Click"> <h2> Add Diagnostic Tests</h2></asp:LinkButton>
        <br />
        <br />
        <asp:GridView ID="Dt_GridView" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True"
            AutoGenerateEditButton="True" DataSourceID="Dt_SqlDataSource" DataKeyNames="Dt_id"
            Style="background-color: #fefefe; background-image: linear-gradient(315deg, #fefefe 0%, #00a4e4 74%);">
            <Columns>
                <asp:BoundField DataField="Dt_id" HeaderText="Dt_id" SortExpression="Dt_id" InsertVisible="False"
                    ReadOnly="True" />
                <asp:BoundField DataField="Dt_title" HeaderText="Dt_title" SortExpression="Dt_title" />
                <asp:BoundField DataField="Dt_desc1" HeaderText="Dt_desc1" SortExpression="Dt_desc1" />
                <asp:BoundField DataField="Dt_desc2" HeaderText="Dt_desc2" SortExpression="Dt_desc2" />
                <asp:ImageField HeaderText="Dt_img" DataImageUrlField="Dt_img" ControlStyle-Width="280px"
                    ControlStyle-Height="280px">
                    <ControlStyle Height="280px" Width="280px"></ControlStyle>
                </asp:ImageField>
            </Columns>
        </asp:GridView>
        <asp:SqlDataSource ID="Dt_SqlDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>"
            SelectCommand="SELECT * FROM [Diagnostic_Tests]" DeleteCommand="Delete from Diagnostic_Tests where Dt_id=@Dt_id;"
            UpdateCommand="Update Diagnostic_Tests set Dt_title=@Dt_title,Dt_desc1=@Dt_desc1,Dt_desc2=@Dt_desc2,Dt_img=@Dt_img where Dt_id=@Dt_id;">
            <DeleteParameters>
                <asp:ControlParameter ControlID="Dt_GridView" Name="Dt_id" PropertyName="SelectedValue" />
            </DeleteParameters>
            <UpdateParameters>
                <asp:ControlParameter ControlID="Dt_GridView" Name="Dt_title" PropertyName="SelectedValue" />
                <asp:ControlParameter ControlID="Dt_GridView" Name="Dt_desc1" PropertyName="SelectedValue" />
                <asp:ControlParameter ControlID="Dt_GridView" Name="Dt_desc2" PropertyName="SelectedValue" />
                <asp:ControlParameter ControlID="Dt_GridView" Name="Dt_img" PropertyName="SelectedValue" />
                <asp:ControlParameter ControlID="Dt_GridView" Name="Dt_id" PropertyName="SelectedValue" />
            </UpdateParameters>
        </asp:SqlDataSource>
    </center>
</asp:Content>
