<%@ Page Title="" Language="C#" MasterPageFile="~/Admin/AdminMasterPage.master" AutoEventWireup="true"
    CodeFile="Admin_ReturnPolicy.aspx.cs" Inherits="Admin_Admin_ReturnPolicy" %>

<%@ OutputCache VaryByParam="none" Duration="1" NoStore="true" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="Server">
    <fieldset style="width: auto; height: auto; background-color: #d5fefd; background-image: linear-gradient(315deg, #d5fefd 0%, #fffcff 74%);">
        <legend>
            <h2 class="shadow3">
            </h2>
        </legend>
        <center>
            <style>
                .shadow3
                {
                    color: black;
                    font: bold 30px Helvetica, Arial, Sans-Serif;
                    text-shadow: 1px 1px white, 2px 2px white, 3px 3px white;
                }
                .shadow3:hover
                {
                    position: relative;
                    top: -3px;
                    left: -3px;
                    text-shadow: 1px 1px white, 2px 2px white, 3px 3px white, 4px 4px white, 5px 5px white, 6px 6px white;
                }
            </style>
            <h4 class="shadow3">
                Return Policy</h4>
    </fieldset>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
    <asp:LinkButton ID="AddRp" runat="server" OnClick="AddRp_Click"><h2> Add Return Policy</h2></asp:LinkButton>
    <br />
    <asp:GridView ID="Rp_GridView" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True"
        AutoGenerateEditButton="True" DataSourceID="Rp_SqlDataSource" Style="background-color: #fefefe;
        background-image: linear-gradient(315deg, #fefefe 0%, #00a4e4 74%);" DataKeyNames="Rp_id">
        <Columns>
            <asp:BoundField DataField="Rp_id" HeaderText="Rp_id" SortExpression="Rp_id" InsertVisible="False"
                ReadOnly="True" />
            <asp:BoundField DataField="Rp_desc1" HeaderText="Rp_desc1" SortExpression="Rp_desc1" />
            <asp:BoundField DataField="Rp_desc2" HeaderText="Rp_desc2" SortExpression="Rp_desc2" />
            <asp:BoundField DataField="Rp_desc3" HeaderText="Rp_desc3" SortExpression="Rp_desc3" />
            <asp:BoundField DataField="Rp_desc4" HeaderText="Rp_desc4" SortExpression="Rp_desc4" />
            <asp:BoundField DataField="Rp_desc5" HeaderText="Rp_desc5" SortExpression="Rp_desc5" />
        </Columns>
    </asp:GridView>
    <asp:SqlDataSource ID="Rp_SqlDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>"
        SelectCommand="SELECT * FROM [Return_Policy]" DeleteCommand="Delete from Return_Policy where Rp_id=@Rp_id;"
        UpdateCommand="Update Return_Policy set Rp_desc1=@Rp_desc1,Rp_desc2=@Rp_desc2,Rp_desc3=@Rp_desc3,Rp_desc4=@Rp_desc4,Rp_desc5=@Rp_desc5 where Rp_id=@Rp_id;">
        <DeleteParameters>
            <asp:ControlParameter ControlID="Rp_GridView" Name="Rp_id" PropertyName="SelectedValue" />
        </DeleteParameters>
        <UpdateParameters>
            <asp:ControlParameter ControlID="Rp_GridView" Name="Rp_desc1" PropertyName="SelectedValue" />
            <asp:ControlParameter ControlID="Rp_GridView" Name="Rp_desc2" PropertyName="SelectedValue" />
            <asp:ControlParameter ControlID="Rp_GridView" Name="Rp_desc3" PropertyName="SelectedValue" />
            <asp:ControlParameter ControlID="Rp_GridView" Name="Rp_desc4" PropertyName="SelectedValue" />
            <asp:ControlParameter ControlID="Rp_GridView" Name="Rp_desc5" PropertyName="SelectedValue" />
            <asp:ControlParameter ControlID="Rp_GridView" Name="Rp_id" PropertyName="SelectedValue" />
        </UpdateParameters>
    </asp:SqlDataSource>
    </center>
</asp:Content>
