<%@ Page Title="" Language="C#" MasterPageFile="~/Admin/AdminMasterPage.master" AutoEventWireup="true"
    CodeFile="Admin_FeedBack.aspx.cs" Inherits="Admin_Admin_FeedBack" %>

<%@ OutputCache VaryByParam="none" Duration="1" NoStore="true" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="Server">
    <fieldset style="width: auto; height: auto; background-color: #d5fefd; background-image: linear-gradient(315deg, #d5fefd 0%, #fffcff 74%);">
        <legend>
            <h2 class="shadow3">
            </h2>
        </legend>
        <center>
            <style>
                .shadow3
                {
                    color: black;
                    font: bold 30px Helvetica, Arial, Sans-Serif;
                    text-shadow: 1px 1px white, 2px 2px white, 3px 3px white;
                }
                .shadow3:hover
                {
                    position: relative;
                    top: -3px;
                    left: -3px;
                    text-shadow: 1px 1px white, 2px 2px white, 3px 3px white, 4px 4px white, 5px 5px white, 6px 6px white;
                }
            </style>
            <h4 class="shadow3">
                FeedBack</h4>
    </fieldset>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
    <asp:GridView ID="F_GridView" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True"
        DataSourceID="F_SqlDataSource" Style="background-color: #fefefe; background-image: linear-gradient(315deg, #fefefe 0%, #00a4e4 74%);"
        DataKeyNames="F_id">
        <Columns>
            <asp:BoundField DataField="F_id" HeaderText="F_id" SortExpression="F_id" InsertVisible="False"
                ReadOnly="True" />
            <asp:BoundField DataField="F_rate" HeaderText="F_rate" SortExpression="F_rate" />
            <asp:BoundField DataField="F_Comm" HeaderText="F_Comm" SortExpression="F_Comm" />
            <asp:BoundField DataField="F_email" HeaderText="F_email" SortExpression="F_email" />
        </Columns>
    </asp:GridView>
    <asp:SqlDataSource ID="F_SqlDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>"
        SelectCommand="SELECT * FROM [Feedback]" DeleteCommand="Delete from Feedback where F_id=@F_id;">
        <DeleteParameters>
            <asp:ControlParameter ControlID="F_GridView" Name="F_id" PropertyName="SelectedValue" />
        </DeleteParameters>
    </asp:SqlDataSource>
    </center>
</asp:Content>
