<%@ Page Title="" Language="C#" MasterPageFile="~/Admin/AdminMasterPage.master" AutoEventWireup="true"
    CodeFile="Admin_Home.aspx.cs" Inherits="Admin_Admin_Home" %>

<%@ OutputCache VaryByParam="none" Duration="1" NoStore="true" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="Server">
    <fieldset style="width: auto; height: auto; background-color: #d5fefd; background-image: linear-gradient(315deg, #d5fefd 0%, #fffcff 74%);">
        <legend>
            <h2 class="shadow3">
            </h2>
        </legend>
        <center>
            <style>
                .shadow3
                {
                    color: black;
                    font: bold 30px Helvetica, Arial, Sans-Serif;
                    text-shadow: 1px 1px white, 2px 2px white, 3px 3px white;
                }
                .shadow3:hover
                {
                    position: relative;
                    top: -3px;
                    left: -3px;
                    text-shadow: 1px 1px white, 2px 2px white, 3px 3px white, 4px 4px white, 5px 5px white, 6px 6px white;
                }
            </style>
            <h4 class="shadow3">
                Home</h4>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
    <center>
        <asp:LinkButton ID="addHome" runat="server" OnClick="addHome_Click"><h3>Add Home</h3></asp:LinkButton>
        <br />
        <%-- <asp:GridView ID="H_GridView" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True"
            AutoGenerateEditButton="True" DataSourceID="H_SqlDataSource" CellPadding="2"
            ForeColor="white" GridLines="Horizontal" BackColor="#2E86C1" BorderColor="black"
            BorderWidth="3px" DataKeyNames="H_id">
            <AlternatingRowStyle BackColor="#2E86C1" />
            <Columns>
                <asp:BoundField DataField="H_id" HeaderText="H_id" SortExpression="H_id" InsertVisible="False"
                    ReadOnly="True" />
                <asp:BoundField DataField="H_desc" HeaderText="H_desc" SortExpression="H_desc" />
                <asp:ImageField HeaderText="H_img" DataImageUrlField="H_img" ControlStyle-Width="500px"
                    ControlStyle-Height="200px">
                </asp:ImageField>
            </Columns>
            <FooterStyle BackColor="#2E86C1" />
            <HeaderStyle BackColor="#1B4F72" Font-Bold="True" />
            <PagerStyle BackColor="#2E86C1" ForeColor="DarkSlateBlue" HorizontalAlign="Center" />
            <SelectedRowStyle BackColor="DarkSlateBlue" ForeColor="GhostWhite" />
            <SortedAscendingCellStyle BackColor="#FAFAE7" />
            <SortedAscendingHeaderStyle BackColor="#DAC09E" />
            <SortedDescendingCellStyle BackColor="#E1DB9C" />
            <SortedDescendingHeaderStyle BackColor="#C2A47B" />
        </asp:GridView>--%>
        <asp:GridView ID="H_GridView" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True"
            AutoGenerateEditButton="True" DataSourceID="H_SqlDataSource" DataKeyNames="H_id"
            Style="background-color: #fefefe; background-image: linear-gradient(315deg, #fefefe 0%, #00a4e4 74%);">
            <Columns>
                <asp:BoundField DataField="H_id" HeaderText="H_id" SortExpression="H_id" InsertVisible="False"
                    ReadOnly="True" />
                <asp:BoundField DataField="H_desc" HeaderText="H_desc" SortExpression="H_desc" />
                <asp:ImageField HeaderText="H_img" DataImageUrlField="H_img" ControlStyle-Width="500px"
                    ControlStyle-Height="200px">
                    <ControlStyle Height="200px" Width="500px"></ControlStyle>
                </asp:ImageField>
            </Columns>
        </asp:GridView>
        <asp:SqlDataSource ID="H_SqlDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>"
            SelectCommand="SELECT * FROM [Home]" DeleteCommand=" Delete from Home where H_id=@H_id;"
            InsertCommand="INSERT INTO [Home] ([H_desc], [H_img]) VALUES (@H_desc, @H_img)"
            UpdateCommand="Update Home set H_desc=@H_desc where H_id=@H_id;">
            <DeleteParameters>
                <asp:ControlParameter ControlID="H_GridView" Name="H_id" PropertyName="SelectedValue" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="H_desc" Type="String" />
                <asp:Parameter Name="H_img" Type="String" />
            </InsertParameters>
            <UpdateParameters>
                <asp:ControlParameter ControlID="H_GridView" Name="H_desc" PropertyName="SelectedValue" />
                <asp:ControlParameter ControlID="H_GridView" Name="H_id" PropertyName="SelectedValue" />
            </UpdateParameters>
        </asp:SqlDataSource>
    </center>
</asp:Content>
