<%@ Page Title="" Language="C#" MasterPageFile="~/Admin/AdminMasterPage.master" AutoEventWireup="true"
    CodeFile="Admin_ContactUs.aspx.cs" Inherits="Admin_Admin_ContactUs" %>

<%@ OutputCache VaryByParam="none" Duration="1" NoStore="true" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="Server">
    <fieldset style="width: auto; height: auto; background-color: #d5fefd; background-image: linear-gradient(315deg, #d5fefd 0%, #fffcff 74%);">
        <legend>
            <h2 class="shadow3">
            </h2>
        </legend>
        <center>
            <style>
                .shadow3
                {
                    color: black;
                    font: bold 30px Helvetica, Arial, Sans-Serif;
                    text-shadow: 1px 1px white, 2px 2px white, 3px 3px white;
                }
                .shadow3:hover
                {
                    position: relative;
                    top: -3px;
                    left: -3px;
                    text-shadow: 1px 1px white, 2px 2px white, 3px 3px white, 4px 4px white, 5px 5px white, 6px 6px white;
                }
            </style>
            <h4 class="shadow3">
                Contact Us</h4>
    </fieldset>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
    <asp:LinkButton ID="addContactus" runat="server" OnClick="addContactus_Click"> <h2> Add Contact Us</h2></asp:LinkButton>
    <br />
    <br />
    <asp:GridView ID="C_GridView" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True"
        AutoGenerateEditButton="True" DataKeyNames="C_id" DataSourceID="C_SqlDataSource"
        Style="background-color: #fefefe; background-image: linear-gradient(315deg, #fefefe 0%, #00a4e4 74%);">
        <Columns>
            <asp:BoundField DataField="C_id" HeaderText="C_id" SortExpression="C_id" InsertVisible="False"
                ReadOnly="True" />
            <asp:BoundField DataField="C_desc" HeaderText="C_desc" SortExpression="C_desc" />
            <asp:BoundField DataField="C_addr" HeaderText="C_addr" SortExpression="C_addr" />
            <asp:BoundField DataField="C_phn" HeaderText="C_phn" SortExpression="C_phn" />
            <asp:BoundField DataField="C_hours" HeaderText="C_hours" SortExpression="C_hours" />
            <asp:BoundField DataField="C_email" HeaderText="C_email" SortExpression="C_email" />
        </Columns>
    </asp:GridView>
    <asp:SqlDataSource ID="C_SqlDataSource" runat="server" ConnectionString="<%$ ConnectionStrings:ConnectionString %>"
        SelectCommand="SELECT * FROM [ContactUs]" DeleteCommand="Delete from ContactUs where C_id=@C_id;"
        UpdateCommand="Update ContactUs set C_desc=@C_desc,C_addr=@C_addr,C_phn=@C_phn,C_hours=@C_hours,C_email=@C_email where C_id=@C_id;"
        InsertCommand="INSERT INTO [ContactUs] ([C_desc], [C_addr], [C_phn], [C_hours], [C_email]) VALUES (@C_desc, @C_addr, @C_phn, @C_hours, @C_email)">
        <DeleteParameters>
            <asp:ControlParameter ControlID="C_GridView" Name="C_id" PropertyName="SelectedValue" />
        </DeleteParameters>
        <InsertParameters>
            <asp:Parameter Name="C_desc" Type="String" />
            <asp:Parameter Name="C_addr" Type="String" />
            <asp:Parameter Name="C_phn" Type="String" />
            <asp:Parameter Name="C_hours" Type="String" />
            <asp:Parameter Name="C_email" Type="String" />
        </InsertParameters>
        <UpdateParameters>
            <asp:ControlParameter ControlID="C_GridView" Name="C_desc" PropertyName="SelectedValue" />
            <asp:ControlParameter ControlID="C_GridView" Name="C_addr" PropertyName="SelectedValue" />
            <asp:ControlParameter ControlID="C_GridView" Name="C_phn" PropertyName="SelectedValue" />
            <asp:ControlParameter ControlID="C_GridView" Name="C_hours" PropertyName="SelectedValue" />
            <asp:ControlParameter ControlID="C_GridView" Name="C_email" PropertyName="SelectedValue" />
            <asp:ControlParameter ControlID="C_GridView" Name="C_id" PropertyName="SelectedValue" />
        </UpdateParameters>
    </asp:SqlDataSource>
    </center>
</asp:Content>
